# Generated by Django 3.0.7 on 2020-06-13 20:03

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('messenger', models.CharField(blank=True, choices=[('media/messengers/telegram-app.png', 'Telegram'), ('media/messengers/viber.png', 'Viber'), ('media/messengers/whatsapp.png', 'Whatsapp')], max_length=250, verbose_name='Мессенджер')),
                ('avatar', models.ImageField(default='profile/default_profile.png', upload_to='profile/', verbose_name='Аватар')),
                ('nickname', models.CharField(max_length=16, verbose_name='Отображаемое имя')),
                ('about', models.TextField(blank=True, max_length=250, verbose_name='О себе')),
                ('contact_phone', phone_field.models.PhoneField(blank=True, max_length=31, null=True, verbose_name='Телефон для связи')),
                ('contact_link', models.URLField(blank=True, null=True, verbose_name='Ссылка для связи')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
